#! /bin/sh

set -e
source /etc/profile
DESC="reach"
NAME=reach
case "$1" in
  start)
        printf "Starting $DESC: "
                echo "Ready to start init..."
                /usr/local/init/init.sh &
        echo "OK"
        ;;
  stop)
        printf "Stopping $DESC: "
        echo "OK"
        ;;
  restart|force-reload)
        echo "Restarting $DESC: "
        echo ""
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
